---
apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.port }}"
    prometheus.io/path: "/metrics"

spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}