apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.backend.configMap }}
  namespace: {{ .Values.namespace.name }}

data:
  POSTGRES_DB: {{ .Values.backendConfigmap.data.POSTGRES_DB | quote }}
  APP_NAME: {{ .Values.backendConfigmap.data.APP_NAME | quote }}
  SCHEDULER_ENABLED: {{ .Values.backendConfigmap.data.SCHEDULER_ENABLED | quote }}
  SMTP_HOST: {{ .Values.backendConfigmap.data.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.backendConfigmap.data.SMTP_PORT | quote }}
  SMTP_STARTTLS: {{ .Values.backendConfigmap.data.SMTP_STARTTLS | quote }}
  FRONTEND_APP_URL: {{ .Values.backendConfigmap.data.FRONTEND_APP_URL | quote }}
  PASSWORD_RESET_MINUTES: {{ .Values.backendConfigmap.data.PASSWORD_RESET_MINUTES | quote }}