apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: {{ .Values.namespace.name }}

data:
  APP_NAME: {{ .Values.app.name }}

  DATABASE_HOST: {{ .Values.postgres.host }}
  DATABASE_PORT: {{ .Values.postgres.port }}
  DATABASE_NAME: {{ .Values.postgres.dbName }}

  CORS_ORIGINS: {{ .Values.configmap.data.CORS_ORIGINS }}

  FRONTEND_APP_URL: {{ .Values.configmap.data.FRONTEND_APP_URL }}

  PASSWORD_RESET_MINUTES: {{ .Values.configmap.data.PASSWORD_RESET_MINUTES }}

  REPORT_STORAGE_PATH: {{ .Values.configmap.data.REPORT_STORAGE_PATH }}

  SCHEDULER_ENABLED: {{ .Values.configmap.data.SCHEDULER_ENABLED }}

  SMTP_HOST: {{ .Values.configmap.data.SMTP_HOST }}
  SMTP_PORT: {{ .Values.configmap.data.SMTP_PORT }}
  SMTP_STARTTLS: {{ .Values.configmap.data.SMTP_STARTTLS }}