apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    app: db

spec:
  replicas: {{ .Values.postgres.replicas }}

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.postgres.port }}

          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName }}
            - name: DATABASE_USER
              value: {{ .Values.postgres.userName }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgres.password }}

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.userName }}
                - -d
                - {{ .Values.postgres.dbName }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.userName }}
                - -d
                - {{ .Values.postgres.dbName }}
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}

            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu }}
              memory: {{ .Values.postgres.resources.limits.memory }}

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: db-pvc
