apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}