apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque

stringData:
  POSTGRES_USER: {{ .Values.backendSecret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.backendSecret.POSTGRES_PASSWORD | quote }}
  DATABASE_URL: {{ .Values.backendSecret.DATABASE_URL | quote }}
  JWT_SECRET_KEY: {{ .Values.backendSecret.JWT_SECRET_KEY | quote }}
  BOOTSTRAP_ADMIN_EMAIL: {{ .Values.backendSecret.BOOTSTRAP_ADMIN_EMAIL | quote }}
  BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.backendSecret.BOOTSTRAP_ADMIN_PASSWORD | quote }}
  SMTP_USERNAME: {{ .Values.backendSecret.SMTP_USERNAME | quote }}
  SMTP_PASSWORD: {{ .Values.backendSecret.SMTP_PASSWORD | quote }}
  SMTP_FROM: {{ .Values.backendSecret.SMTP_FROM | quote }}