apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque

stringData:

  DATABASE_USER: {{ .Values.backendSecret.DATABASE_USER | quote }}
  DATABASE_PASSWORD: {{ .Values.backendSecret.DATABASE_PASSWORD | quote }}
  JWT_SECRET_KEY: {{ .Values.backendSecret.JWT_SECRET_KEY | quote }}
  BOOTSTRAP_ADMIN_EMAIL: {{ .Values.backendSecret.BOOTSTRAP_ADMIN_EMAIL | quote }}
  BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.backendSecret.BOOTSTRAP_ADMIN_PASSWORD | quote }}
  SMTP_USERNAME: {{ .Values.backendSecret.SMTP_USERNAME | quote }}
  SMTP_PASSWORD: {{ .Values.backendSecret.SMTP_PASSWORD | quote }}
  SMTP_FROM: {{ .Values.backendSecret.SMTP_FROM | quote }}