apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  POSTGRES_USER: charity
  POSTGRES_PASSWORD: password

  JWT_SECRET_KEY: your-super-secret-key

  BOOTSTRAP_ADMIN_EMAIL: admin@charity.local
  BOOTSTRAP_ADMIN_PASSWORD: adminpassword

  SMTP_USERNAME: your-email@gmail.com
  SMTP_PASSWORD: your-app-password
  SMTP_FROM: your-email@gmail.com