#SPDX-License-Identifier: MIT-0
---
# tasks file for transfer_files

## TODO: make this private repo and add access token to ansible vault for authentication
- name: Clone baytak repository
  ansible.builtin.git:
    repo: https://github.com/AbdelwahabAdam/Baytak_Foundation_Management.git
    dest: /opt/baytak
    version: main
    update: true
    force: true

- name: Create reports directory
  file:
    path: /data/report_data
    state: directory
    owner: 100
    group: 101
    mode: "0775"


- name: Deploy Baytak
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: true
    name: baytak
    chart_ref: /opt/baytak/helm
    release_namespace: baytak
    release_state: present
    create_namespace: true

    values_files:
      - /opt/baytak/helm/values.yaml

    values:
      backendSecret:
        DATABASE_USER: "{{ DATABASE_USER }}"
        DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"
        JWT_SECRET_KEY: "{{ JWT_SECRET_KEY }}"
        BOOTSTRAP_ADMIN_EMAIL: "{{ BOOTSTRAP_ADMIN_EMAIL }}"
        BOOTSTRAP_ADMIN_PASSWORD: "{{ BOOTSTRAP_ADMIN_PASSWORD }}"
        SMTP_USERNAME: "{{ SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ SMTP_PASSWORD }}"
        SMTP_FROM: "{{ SMTP_FROM }}"
      registry:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_token }}"
        email: "{{ dockerhub_email }}"







# - name: Copy .env file to /opt/baytak/
#   ansible.builtin.copy:
#     src: "/home/hopa/baytak/Baytak_Foundation_Management/.env"
#     dest: /opt/baytak/.env
#     owner: ubuntu
#     group: ubuntu
#     mode: "0600"


# - name: Create Docker registry secret
#   kubernetes.core.k8s:
#     wait: true
#     kubeconfig: /etc/rancher/k3s/k3s.yaml
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: regcred
#         namespace: baytak
#       type: kubernetes.io/dockerconfigjson
#       stringData:
#         .dockerconfigjson: |
#           {
#             "auths": {
#               "https://index.docker.io/v1/": {
#                 "username": "{{ dockerhub_username }}",
#                 "password": "{{ dockerhub_token }}",
#                 "email": "{{ dockerhub_email }}",
#                 "auth": "{{ (dockerhub_username ~ ':' ~ dockerhub_token) | b64encode }}"
#               }
#             }
#           }


# - name: Create backend secret
#   kubernetes.core.k8s:
#     wait: true
#     kubeconfig: /etc/rancher/k3s/k3s.yaml
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: backend-secret
#         namespace: baytak
#       type: Opaque
#       stringData:
#         POSTGRES_USER: "{{ POSTGRES_USER }}"
#         POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
#         JWT_SECRET_KEY: "{{ JWT_SECRET_KEY }}"
#         BOOTSTRAP_ADMIN_EMAIL: "{{ BOOTSTRAP_ADMIN_EMAIL }}"
#         BOOTSTRAP_ADMIN_PASSWORD: "{{ BOOTSTRAP_ADMIN_PASSWORD }}"
#         SMTP_USERNAME: "{{ SMTP_USERNAME }}"
#         SMTP_PASSWORD: "{{ SMTP_PASSWORD }}"
#         SMTP_FROM: "{{ SMTP_FROM }}"

