apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: baytak
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/postgres
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: baytak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deployment
  namespace: baytak
  labels:
    app: db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: "charity"
            - name: POSTGRES_USER
              value: "charity"
            - name: POSTGRES_PASSWORD
              value: "password"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - charity
                - -d
                - charity
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - charity
                - -d
                - charity
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: db-pvc

--- 
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: baytak
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432