import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

import { brand } from './branding'

export type Locale = 'en' | 'ar'

const localeStorageKey = 'baytak-locale'

const arabic: Record<string, string> = {
  'Open navigation': 'فتح القائمة',
  'Close navigation': 'إغلاق القائمة',
  'Collapse navigation': 'طيّ القائمة',
  'Expand navigation': 'توسيع القائمة',
  'Language selector': 'اختيار اللغة',
  'Sign out': 'تسجيل الخروج',
  'Workspace': 'مساحة العمل',
  'Overview': 'نظرة عامة',
  'Donors': 'المتبرعون',
  'Donations': 'التبرعات',
  'Donation types': 'أنواع التبرعات',
  'Custody': 'العُهد',
  'Approvals': 'الموافقات',
  'Reports': 'التقارير',
  'Scheduled reports': 'التقارير المجدولة',
  'Users': 'المستخدمون',
  'Settings': 'الإعدادات',
  'Loading data…': 'جارٍ تحميل البيانات…',
  'Loading your workspace…': 'جارٍ تحميل مساحة العمل…',
  'Close': 'إغلاق',
  'Cancel': 'إلغاء',
  'Edit': 'تعديل',
  'Save changes': 'حفظ التغييرات',
  'Saving…': 'جارٍ الحفظ…',
  'Create': 'إنشاء',
  'Actions': 'الإجراءات',
  'Status': 'الحالة',
  'Active': 'نشط',
  'Inactive': 'غير نشط',
  'active': 'نشط',
  'inactive': 'غير نشط',
  'confirmed': 'مؤكد',
  'cancelled': 'ملغى',
  'refunded': 'مسترد',
  'pending': 'قيد الانتظار',
  'approved': 'موافق عليه',
  'rejected': 'مرفوض',
  'closed': 'مغلق',
  'Staff sign in': 'تسجيل دخول الموظفين',
  'Community-first giving': 'عطاء يضع المجتمع أولاً',
  'Every act of generosity deserves a clear purpose.': 'كل عمل من أعمال العطاء يستحق هدفاً واضحاً.',
  'We connect thoughtful donors with practical community support—food, medical aid, education, and urgent relief—while keeping every contribution accountable.': 'نربط المتبرعين الكرام بالدعم العملي للمجتمع — الغذاء، والمساعدة الطبية، والتعليم، والإغاثة العاجلة — مع ضمان توثيق كل مساهمة.',
  'Get in touch': 'تواصل معنا',
  'See our impact': 'شاهد أثرنا',
  'active programs': 'برامج نشطة',
  'traceable giving': 'عطاء قابل للتتبع',
  'Local': 'محلي',
  'community focus': 'تركيز مجتمعي',
  'What we support': 'ما ندعمه',
  'Practical care where it matters most.': 'رعاية عملية حيث تكون الحاجة أكبر.',
  'Our programmes are shaped by local needs and delivered with dignity.': 'تتشكّل برامجنا وفق الاحتياجات المحلية وتُقدّم بكرامة.',
  'Food & essentials': 'الغذاء والاحتياجات الأساسية',
  'Reliable food parcels and essential supplies for families facing hardship.': 'سلال غذائية موثوقة واحتياجات أساسية للعائلات التي تواجه صعوبات.',
  'Education': 'التعليم',
  'Learning materials and opportunity for children to thrive.': 'مواد تعليمية وفرص تساعد الأطفال على الازدهار.',
  'Medical support': 'الدعم الطبي',
  'Urgent assistance with treatment, medicine, and recovery.': 'مساعدة عاجلة للعلاج والدواء والتعافي.',
  'Let’s make an impact': 'لنصنع أثراً',
  'Have a question or want to support a program?': 'هل لديك سؤال أو ترغب في دعم برنامج؟',
  'Welcome back': 'مرحباً بعودتك',
  'Good work starts with a clear record.': 'العمل الجيد يبدأ بسجل واضح.',
  'Sign in to manage the people, gifts, and funds entrusted to your organisation.': 'سجّل الدخول لإدارة الأشخاص والتبرعات والأموال الموكلة إلى مؤسستك.',
  'Secure sign in': 'تسجيل دخول آمن',
  'Access your workspace': 'الوصول إلى مساحة العمل',
  'Use the administrator account configured for this environment.': 'استخدم حساب المسؤول المُعدّ لهذه البيئة.',
  'Email': 'البريد الإلكتروني',
  'Password': 'كلمة المرور',
  'Signing in…': 'جارٍ تسجيل الدخول…',
  'Sign in': 'تسجيل الدخول',
  'Forgot password?': 'هل نسيت كلمة المرور؟',
  'Account recovery': 'استعادة الحساب',
  'Keep access to the work that matters.': 'حافظ على الوصول إلى العمل المهم.',
  'Use your organisation email to securely restore access to your account.': 'استخدم بريد مؤسستك لاستعادة الوصول إلى حسابك بأمان.',
  'Password reset': 'إعادة تعيين كلمة المرور',
  'Reset your password': 'إعادة تعيين كلمة المرور',
  'We will email a secure, time-limited reset link to your organisation address.': 'سنرسل رابطاً آمناً ومحدود المدة لإعادة التعيين إلى بريد مؤسستك.',
  'Check your email': 'تحقق من بريدك الإلكتروني',
  'Sending…': 'جارٍ الإرسال…',
  'Send reset link': 'إرسال رابط إعادة التعيين',
  'Back to sign in': 'العودة إلى تسجيل الدخول',
  'Choose a new password': 'اختر كلمة مرور جديدة',
  'Set a new password': 'تعيين كلمة مرور جديدة',
  'Confirm new password': 'تأكيد كلمة المرور الجديدة',
  'The two passwords do not match.': 'كلمتا المرور غير متطابقتين.',
  'This password reset link is invalid or incomplete.': 'رابط إعادة تعيين كلمة المرور غير صالح أو غير مكتمل.',
  'Updating…': 'جارٍ التحديث…',
  'Password updated': 'تم تحديث كلمة المرور',
  'Password updated. Please sign in with your new password.': 'تم تحديث كلمة المرور. يرجى تسجيل الدخول بكلمة المرور الجديدة.',
  'If an active account uses that email, a password reset link has been sent.': 'إذا كان هناك حساب نشط يستخدم هذا البريد، فقد تم إرسال رابط إعادة تعيين كلمة المرور.',
  'Operations overview': 'نظرة عامة على العمليات',
  'Good morning.': 'صباح الخير.',
  'Here is what is happening across your charity.': 'إليك ما يحدث في مؤسستك الخيرية.',
  'day': 'يوم',
  'week': 'أسبوع',
  'month': 'شهر',
  'Donations received': 'التبرعات المستلمة',
  'confirmed in period': 'مؤكدة خلال الفترة',
  'Active donors': 'المتبرعون النشطون',
  'gave in this period': 'تبرعوا خلال هذه الفترة',
  'Custody available': 'العُهدة المتاحة',
  'after approved expenses': 'بعد المصروفات المعتمدة',
  'Pending approvals': 'الموافقات المعلقة',
  'awaiting a decision': 'بانتظار قرار',
  'Giving by fund': 'التبرعات حسب الصندوق',
  'Confirmed donations for the selected period.': 'التبرعات المؤكدة للفترة المحددة.',
  'No donations yet': 'لا توجد تبرعات بعد',
  'Donation totals will appear here.': 'ستظهر إجماليات التبرعات هنا.',
  'Recently active donors': 'المتبرعون النشطون مؤخراً',
  'People who gave most recently.': 'الأشخاص الذين تبرعوا مؤخراً.',
  'No activity yet': 'لا يوجد نشاط بعد',
  'New donors will appear here.': 'سيظهر المتبرعون الجدد هنا.',
  'Donation distribution': 'توزيع التبرعات',
  'See the balance of support across active funds.': 'شاهد توازن الدعم بين الصناديق النشطة.',
  'No donation data yet': 'لا توجد بيانات تبرعات بعد',
  'Record a donation to start seeing distribution.': 'سجّل تبرعاً لعرض التوزيع.',
  'Relationships': 'العلاقات',
  'Keep complete, searchable records of the people who support your work.': 'احتفظ بسجلات كاملة وقابلة للبحث للأشخاص الذين يدعمون عملك.',
  'Add donor': 'إضافة متبرع',
  'Search by donor name': 'ابحث باسم المتبرع',
  'Phone': 'الهاتف',
  'Donor ID': 'معرّف المتبرع',
  'Clear filters': 'مسح عوامل التصفية',
  'Donor': 'المتبرع',
  'Giving to date': 'إجمالي التبرعات',
  'Last fund': 'آخر صندوق',
  'Added': 'تاريخ الإضافة',
  'Archive': 'أرشفة',
  'No donors found': 'لم يتم العثور على متبرعين',
  'Adjust the filters or add a donor to begin.': 'عدّل عوامل التصفية أو أضف متبرعاً للبدء.',
  'Edit donor': 'تعديل متبرع',
  'Add a donor': 'إضافة متبرع',
  'First name': 'الاسم الأول',
  'Last name': 'اسم العائلة',
  'Primary phone': 'الهاتف الرئيسي',
  'City': 'المدينة',
  'Address': 'العنوان',
  'Country': 'الدولة',
  'Save donor': 'حفظ المتبرع',
  'Create donor': 'إنشاء متبرع',
  'Fund setup': 'إعداد الصناديق',
  'Define the funds and causes donors can support.': 'حدّد الصناديق والمجالات التي يمكن للمتبرعين دعمها.',
  'Add type': 'إضافة نوع',
  'No description supplied for this fund.': 'لا يوجد وصف لهذا الصندوق.',
  'Deactivate': 'إلغاء التفعيل',
  'No donation types': 'لا توجد أنواع تبرعات',
  'Create a fund before recording a donation.': 'أنشئ صندوقاً قبل تسجيل تبرع.',
  'Edit donation type': 'تعديل نوع التبرع',
  'Add donation type': 'إضافة نوع تبرع',
  'Fund name': 'اسم الصندوق',
  'Description': 'الوصف',
  'Active and available for new donations': 'نشط ومتاح للتبرعات الجديدة',
  'Create type': 'إنشاء نوع',
  'Income records': 'سجلات الإيرادات',
  'Record contributions accurately and keep every receipt traceable.': 'سجّل المساهمات بدقة وحافظ على إمكانية تتبع كل إيصال.',
  'Record donation': 'تسجيل تبرع',
  'All donors': 'كل المتبرعين',
  'All types': 'كل الأنواع',
  'All statuses': 'كل الحالات',
  'Confirmed': 'مؤكد',
  'Cancelled': 'ملغى',
  'Refunded': 'مسترد',
  'Minimum amount': 'الحد الأدنى للمبلغ',
  'Maximum amount': 'الحد الأقصى للمبلغ',
  'From': 'من',
  'To': 'إلى',
  'Date': 'التاريخ',
  'Fund': 'الصندوق',
  'Receipt': 'الإيصال',
  'Amount': 'المبلغ',
  'No donations found': 'لم يتم العثور على تبرعات',
  'Adjust the filters or record a donation.': 'عدّل عوامل التصفية أو سجّل تبرعاً.',
  'Edit donation': 'تعديل تبرع',
  'Choose a donor': 'اختر متبرعاً',
  'Choose a fund': 'اختر صندوقاً',
  'Currency': 'العملة',
  'Received at': 'تاريخ الاستلام',
  'Payment method': 'طريقة الدفع',
  'Record status': 'حالة السجل',
  'Receipt number': 'رقم الإيصال',
  'Save donation': 'حفظ التبرع',
  'Expense funds': 'أموال العُهد',
  'Assign funds, monitor available balance, and review submitted expenses.': 'عيّن الأموال، وراقب الرصيد المتاح، وراجع المصروفات المقدمة.',
  'View the funds assigned to you and their remaining balance.': 'اعرض الأموال المسندة إليك ورصيدها المتبقي.',
  'Assign custody': 'تعيين عُهدة',
  'Assigned amount': 'المبلغ المعيّن',
  'Available': 'المتاح',
  'Recipient': 'المستلم',
  'Assigned by': 'عيّن بواسطة',
  'Assigned': 'تاريخ التعيين',
  'Expenses': 'المصروفات',
  'No assignment description.': 'لا يوجد وصف للعُهدة.',
  'Submit expense': 'تقديم مصروف',
  'No custody assigned': 'لا توجد عُهد مسندة',
  'Assign custody to a user when they need funds for expenses.': 'عيّن عُهدة لمستخدم عندما يحتاج إلى أموال للمصروفات.',
  'An assigned fund will appear here.': 'سيظهر الصندوق المعيّن هنا.',
  'Choose a user': 'اختر مستخدماً',
  'Assigned at': 'تاريخ التعيين',
  'Purpose or usage guidance': 'الغرض أو إرشادات الاستخدام',
  'Save custody': 'حفظ العُهدة',
  'Submit custody expense': 'تقديم مصروف عُهدة',
  'Expense title': 'عنوان المصروف',
  'Expense date': 'تاريخ المصروف',
  'Submit for approval': 'إرسال للموافقة',
  'Financial review': 'المراجعة المالية',
  'Review submitted expenses before they reduce available custody.': 'راجع المصروفات المقدمة قبل أن تخصم من العُهدة المتاحة.',
  'Expense': 'المصروف',
  'Assignment': 'العُهدة',
  'Submitted': 'تاريخ التقديم',
  'Decision': 'القرار',
  'Reject': 'رفض',
  'Approve': 'موافقة',
  'Nothing awaiting approval': 'لا يوجد ما ينتظر الموافقة',
  'New expense submissions will appear here.': 'ستظهر طلبات المصروفات الجديدة هنا.',
  'Access control': 'التحكم في الوصول',
  'Manage team members and their access to financial records.': 'أدر أعضاء الفريق وصلاحيات وصولهم إلى السجلات المالية.',
  'Add user': 'إضافة مستخدم',
  'Team member': 'عضو الفريق',
  'Roles': 'الأدوار',
  'Created': 'تاريخ الإنشاء',
  'Add team member': 'إضافة عضو فريق',
  'Create user': 'إنشاء مستخدم',
  'Your account': 'حسابك',
  'Profile & settings': 'الملف الشخصي والإعدادات',
  'Update your contact details and keep your account secure.': 'حدّث بيانات الاتصال وحافظ على أمان حسابك.',
  'Personal details': 'البيانات الشخصية',
  'How your name appears on operational records.': 'كيف يظهر اسمك في السجلات التشغيلية.',
  'Phone number': 'رقم الهاتف',
  'Security': 'الأمان',
  'Use a unique password with at least 8 characters.': 'استخدم كلمة مرور فريدة من 8 أحرف على الأقل.',
  'Current password': 'كلمة المرور الحالية',
  'New password': 'كلمة المرور الجديدة',
  'Update password': 'تحديث كلمة المرور',
  'Your profile was updated.': 'تم تحديث ملفك الشخصي.',
  'Password updated. Please sign in again to continue.': 'تم تحديث كلمة المرور. يرجى تسجيل الدخول مرة أخرى للمتابعة.',
  'Insights & exports': 'الإحصاءات والتصدير',
  'Generate a CSV export for a specific reporting period.': 'أنشئ ملف CSV لفترة تقارير محددة.',
  'Manual export': 'تصدير يدوي',
  'Build a time-bound report': 'إنشاء تقرير لفترة زمنية',
  'Choose the report contents and a start/end date. The exported CSV includes only records in that reporting window.': 'اختر محتوى التقرير وتاريخ البداية والنهاية. يتضمن ملف CSV السجلات ضمن فترة التقرير فقط.',
  'Report contents': 'محتوى التقرير',
  'Donation ledger': 'سجل التبرعات',
  'Donor summary': 'ملخص المتبرعين',
  'Custody assignments': 'تعيينات العُهد',
  'Start date': 'تاريخ البداية',
  'End date': 'تاريخ النهاية',
  'Choose both dates before generating a report.': 'اختر التاريخين قبل إنشاء التقرير.',
  'Generating…': 'جارٍ الإنشاء…',
  'Generate CSV': 'إنشاء CSV',
  'Generated reports': 'التقارير المنشأة',
  'Files are kept in the local application report volume.': 'تُحفظ الملفات في وحدة تخزين التقارير المحلية للتطبيق.',
  'Download': 'تنزيل',
  'No reports generated': 'لا توجد تقارير منشأة',
  'Your generated files will appear here.': 'ستظهر ملفاتك المنشأة هنا.',
  'Automated delivery': 'تسليم آلي',
  'Create recurring CSV reports and send them through your configured SMTP server.': 'أنشئ تقارير CSV متكررة وأرسلها عبر خادم SMTP المُعدّ.',
  'Schedule report': 'جدولة تقرير',
  'Run now': 'تشغيل الآن',
  'Name': 'الاسم',
  'Report': 'التقرير',
  'Window': 'الفترة',
  'Recipients': 'المستلمون',
  'Next run': 'التشغيل القادم',
  'Disable': 'تعطيل',
  'No scheduled reports': 'لا توجد تقارير مجدولة',
  'Schedule a recurring report for finance or leadership.': 'جدوِل تقريراً متكرراً للمالية أو الإدارة.',
  'Edit scheduled report': 'تعديل التقرير المجدول',
  'Schedule a report': 'جدولة تقرير',
  'Schedule name': 'اسم الجدول',
  'Frequency': 'التكرار',
  'Weekly': 'أسبوعي',
  'Monthly': 'شهري',
  'Yearly': 'سنوي',
  'Reporting window': 'فترة التقرير',
  'Previous 7 days': 'الـ 7 أيام السابقة',
  'Previous 30 days': 'الـ 30 يوماً السابقة',
  'Previous 365 days': 'الـ 365 يوماً السابقة',
  'Email recipients': 'البريد الإلكتروني للمستلمين',
  'Active schedule': 'جدول نشط',
  'Create schedule': 'إنشاء جدول',
  'SMTP delivery uses the': 'إرسال SMTP يستخدم قيم',
  'values in `.env`. Use': 'الموجودة في `.env`. استخدم',
  'to test a schedule immediately.': 'لاختبار الجدول فوراً.',
  'About us': 'من نحن',
  'Our projects': 'مشاريعنا',
  'Contact': 'تواصل معنا',
  'About Baytak': 'عن بيتك',
  'Activities': 'الأنشطة',
  'Projects': 'المشاريع',
  'Services': 'الخدمات',
  'Volunteer': 'التطوع',
  'Donate now': 'تبرع الآن',
  'Together, We Restore Hope.': 'معا، نُعيد الأمل.',
  'Practical charity for families in need — feeding, medical care, education, and community support delivered with dignity.': 'عمل خيري عملي للأسر المحتاجة — إطعام، ورعاية طبية، وتعليم، ودعم مجتمعي يُقدَّم بكرامة.',
  'Donate': 'تبرع',
  'Calculate your zakat': 'احسب زكاتك',
  'Volunteer with Baytak': 'التطوع مع بيتك',
  'Give today': 'تبرّع اليوم',
  'Daily sadaqa · 20 EGP': 'صدقة يومية · 20 جنيه',
  'Start with a simple daily gift, or choose a monthly share for feeding, education, or community support.': 'ابدأ بصدقة يومية بسيطة، أو اختر سهماً شهرياً للإطعام أو التعليم أو دعم المجتمع.',
  '20 EGP daily': '20 جنيهاً يومياً',
  'Monthly share': 'سهم شهري',
  'Flexible gift': 'تبرع مرن',
  'Open donation card': 'افتح بطاقة التبرع',
  'A home for compassionate community support.': 'بيت للدعم المجتمعي الرحيم.',
  'Baytak Foundation is a community-focused charitable initiative. We distribute zakat, feed families, support medical needs, sustain ongoing charities, and invest in educational sponsorships.': 'مؤسسة بيتك مبادرة خيرية تركز على المجتمع. نوزّع الزكاة، ونطعم الأسر، وندعم الاحتياجات الطبية، ونستمر في الصدقات الجارية، ونستثمر في الكفالات التعليمية.',
  'Community first': 'المجتمع أولاً',
  'Baytak exists to turn generosity into practical support for families facing everyday hardship.': 'توجد بيتك لتحويل العطاء إلى دعم عملي للأسر التي تواجه صعوبات يومية.',
  'Direct impact': 'أثر مباشر',
  'From feeding and zakat to medical care and education, every programme is built around real needs.': 'من الإطعام والزكاة إلى الرعاية الطبية والتعليم، يُبنى كل برنامج حول احتياجات حقيقية.',
  'Trusted stewardship': 'أمانة موثوقة',
  'We aim for clear reporting, careful custody of funds, and support delivered with dignity.': 'نسعى لتقارير واضحة، وعهدة دقيقة للأموال، ودعم يُقدَّم بكرامة.',
  'About Baytak image placeholder': 'مساحة صورة عن بيتك',
  'Baytak activities': 'أنشطة بيتك',
  'Where generosity becomes action.': 'حيث يتحول العطاء إلى عمل.',
  'Our core activities turn donations into tangible support for people and families.': 'تحوّل أنشطتنا الأساسية التبرعات إلى دعم ملموس للأفراد والأسر.',
  'Zakat distribution': 'توزيع زكاة مال',
  'Delivering zakat funds to eligible families with care and accountability.': 'إيصال أموال الزكاة إلى الأسر المستحقة بعناية ومساءلة.',
  'Feeding': 'إطعام',
  'Food parcels and meals for households facing food insecurity.': 'سلال غذائية ووجبات للأسر التي تواجه انعداماً في الأمن الغذائي.',
  'Medical services': 'خدمات طبية',
  'Supporting treatment pathways, exams, and recovery for patients in need.': 'دعم مسارات العلاج والفحوصات والتعافي للمرضى المحتاجين.',
  'Ongoing charities': 'صدقات جارية',
  'Sadaqa jariya projects that continue to benefit communities over time.': 'مشاريع صدقة جارية تستمر في نفع المجتمعات عبر الزمن.',
  'Educational sponsorships': 'كفالات تعليمية',
  'Helping students stay in school through sustained educational support.': 'مساعدة الطلاب على الاستمرار في التعليم عبر دعم تعليمي مستمر.',
  'Baytak projects': 'مشاريع بيتك',
  'The workshop · المشغل': 'المشغل',
  'The Baytak workshop is a flagship project that builds livelihood pathways, skills, and sustainable community value. It stands alongside our aid programmes as a longer-term investment in dignity and opportunity.': 'مشغل بيتك مشروع رائد يبني مسارات رزق ومهارات وقيمة مجتمعية مستدامة. يقف إلى جانب برامج الإغاثة كاستثمار أطول أجلاً في الكرامة والفرصة.',
  'Skills development and productive work opportunities': 'تنمية المهارات وفرص العمل المنتج',
  'Support for local families through sustained activity': 'دعم للأسر المحلية عبر نشاط مستمر',
  'A practical project visitors can follow and fund': 'مشروع عملي يمكن للزوار متابعته ودعمه',
  'Baytak workshop image placeholder': 'مساحة صورة لمشغل بيتك',
  'Support this project': 'ادعم هذا المشروع',
  'Baytak services': 'خدمات بيتك',
  'Medical care that reaches people in need.': 'رعاية طبية تصل إلى المحتاجين.',
  'Specialised medical services help patients access treatment, exams, and financial relief for care debts.': 'تساعد الخدمات الطبية المتخصصة المرضى على الوصول إلى العلاج والفحوصات، وتخفيف أعباء ديون الرعاية.',
  'Monthly treatment service': 'خدمة العلاج الشهري',
  'Ongoing support for patients who need regular monthly medical care.': 'دعم مستمر للمرضى الذين يحتاجون رعاية طبية شهرية منتظمة.',
  'Medical exams & tests': 'الكشف الطبي والفحوصات',
  'Helping cover check-ups, lab work, and diagnostic examinations.': 'المساعدة في تغطية الكشوفات والتحاليل والفحوصات التشخيصية.',
  'Settling patient debts': 'سداد ديون المرضى للعلاج أو العمليات',
  'Assisting with outstanding treatment or surgery debts for patients in need.': 'المساعدة في سداد ديون العلاج أو العمليات للمرضى المحتاجين.',
  'Medical sponsorships': 'كفالات مرضية',
  'Longer-term sponsorships that keep essential medical care within reach.': 'كفالات أطول أجلاً تُبقي الرعاية الطبية الأساسية في متناول اليد.',
  'Choose a donation type and checkout.': 'اختر نوع التبرع وأتمم الدفع.',
  'Add daily sadaqa, monthly shares, flexible gifts, operating support, or calculated zakat to your cart — then complete checkout.': 'أضف صدقة يومية أو أسهماً شهرية أو تبرعات مرنة أو دعم التشغيل أو الزكاة المحسوبة إلى سلتك — ثم أتمم الدفع.',
  'Quick giving': 'عطاء سريع',
  'Start with a simple gift': 'ابدأ بهدية بسيطة',
  'Daily sadaqa': 'صدقة يومية',
  'A fixed daily charity of 20 EGP.': 'صدقة يومية ثابتة بقيمة 20 جنيهاً.',
  'Monthly shares': 'أسهم شهرية',
  'Sustain families every month': 'ادعم الأسر كل شهر',
  'Monthly share · Feeding': 'سهم شهري · إطعام',
  'A monthly share that helps feed families in need.': 'سهم شهري يساعد على إطعام الأسر المحتاجة.',
  'Monthly share · Educational sponsorship': 'سهم شهري · كفالة تعليمية',
  'Support a student’s education with a monthly sponsorship share.': 'ادعم تعليم طالب عبر سهم كفالة شهري.',
  'Monthly share · Quran & needy support': 'سهم شهري · دعم دور القرآن والمحتاجين',
  'Support Quran centres or help people in urgent need.': 'ادعم دور القرآن أو ساعد المحتاجين في حالات الطوارئ.',
  'Flexible support': 'دعم مرن',
  'Where the need is greatest': 'حيث تكون الحاجة أكبر',
  'Flexible donation': 'تبرع مرن للأنشطة الأكثر احتياجاً',
  'Directed to the activities with the greatest need.': 'يوجَّه إلى الأنشطة الأكثر احتياجاً.',
  'Operating expenses share': 'سهم مصاريف التشغيل',
  'Help cover the operational costs that keep Baytak running.': 'ساهم في تغطية تكاليف التشغيل التي تُبقي بيتك قادرة على العمل.',
  'Amount (EGP)': 'المبلغ (جنيه)',
  'Add': 'أضف',
  'Estimate what you owe, then add it to your donation': 'قدّر ما عليك ثم أضفه إلى تبرعك',
  'Enter approximate assets in EGP. Zakat is calculated at 2.5% of eligible wealth.': 'أدخل تقريباً أصولك بالجنيه. تُحسب الزكاة بنسبة 2.5% من المال الخاضع للزكاة.',
  'Cash & savings': 'النقد والمدخرات',
  'Gold & silver value': 'قيمة الذهب والفضة',
  'Debts': 'الديون',
  'Estimated zakat due': 'الزكاة التقديرية المستحقة',
  'Add zakat to cart': 'أضف الزكاة إلى السلة',
  'Your donation': 'تبرعك',
  'Checkout cart': 'سلة الدفع',
  'Close cart': 'إغلاق السلة',
  'Select a donation type to begin.': 'اختر نوع التبرع للبدء.',
  'Total': 'الإجمالي',
  'Proceed to checkout': 'المتابعة للدفع',
  'Open donation cart': 'افتح سلة التبرع',
  'Complete your donation': 'أتمم تبرعك',
  'Full name': 'الاسم الكامل',
  'Your full name': 'اسمك الكامل',
  'Preferred payment': 'طريقة الدفع المفضلة',
  'Bank transfer': 'تحويل بنكي',
  'Cash handover': 'تسليم نقدي',
  'Mobile wallet': 'محفظة إلكترونية',
  'Notes': 'ملاحظات',
  'Any preference for how this donation should be used': 'أي تفضيل لكيفية استخدام هذا التبرع',
  'Back': 'رجوع',
  'Confirm donation request': 'تأكيد طلب التبرع',
  'Your donation request was received. Our team will contact you shortly to complete checkout and payment.': 'تم استلام طلب تبرعك. سيتواصل معك فريقنا قريباً لإتمام الدفع.',
  'Zakat': 'زكاة',
  'Calculated zakat contribution.': 'مساهمة زكاة محسوبة.',
  'What we have achieved': 'ما تم إنجازه من أنشطة',
  'Activities completed with your support.': 'أنشطة أُنجزت بدعمكم.',
  'These figures reflect the scale of Baytak’s community work and will continue to grow as programmes expand.': 'تعكس هذه الأرقام حجم عمل بيتك المجتمعي، وستستمر في النمو مع توسّع البرامج.',
  'Families supported': 'أسر مدعومة',
  'Through food, medical, and emergency aid': 'عبر الغذاء والرعاية الطبية والإغاثة',
  'Food parcels': 'سلال غذائية',
  'Distributed across community programmes': 'وُزعت عبر البرامج المجتمعية',
  'Medical cases': 'حالات طبية',
  'Exams, treatment support, and sponsorships': 'فحوصات ودعم علاج وكفالات',
  'Students supported through learning pathways': 'طلاب مدعومون عبر مسارات تعليمية',
  'Active volunteers': 'متطوعون نشطون',
  'Field and programme support': 'دعم ميداني وبرنامجي',
  'Ongoing projects': 'مشاريع جارية',
  'Including the Baytak workshop': 'بما في ذلك مشغل بيتك',
  'Reviews': 'آراء المستفيدين',
  'Voices from the Baytak community.': 'أصوات من مجتمع بيتك.',
  'Beneficiary': 'المستفيد',
  'Community donor': 'متبرع',
  'Give your time where it matters.': 'قدّم وقتك حيث يحدث فرقاً.',
  'Join field distribution, medical accompaniment, workshop support, or community outreach. Tell us how you would like to help.': 'انضم إلى التوزيع الميداني أو المرافقة الطبية أو دعم المشغل أو التوعية المجتمعية. أخبرنا كيف تود المساعدة.',
  'How can you help?': 'كيف يمكنك المساعدة؟',
  'Skills, availability, or preferred activity': 'المهارات أو التوفر أو النشاط المفضل',
  'Join as a volunteer': 'انضم كمتطوع',
  'Volunteer registration is being configured. Please email us to join the next opportunity.': 'يجري إعداد تسجيل المتطوعين. يرجى مراسلتنا عبر البريد للانضمام إلى الفرصة القادمة.',
  'Contact us': 'تواصل معنا',
  'Let’s create a better future together.': 'لنصنع مستقبلاً أفضل معاً.',
  'Reach out about donations, volunteering, medical services, or partnership with Baytak.': 'تواصل معنا بخصوص التبرعات أو التطوع أو الخدمات الطبية أو الشراكة مع بيتك.',
  'WhatsApp contact to be added': 'سيُضاف رقم واتساب للتواصل',
  'Address and service locations to be added': 'سيُضاف العنوان ومواقع الخدمة',
  'How can we help?': 'كيف يمكننا مساعدتك؟',
  'Your name': 'اسمك',
  'Tell us how you would like to support Baytak Foundation': 'أخبرنا كيف تود دعم مؤسسة بيتك',
  'Send message': 'إرسال الرسالة',
  'Form delivery is being configured. Please contact the foundation by email in the meantime.': 'يجري إعداد إرسال النموذج. يرجى التواصل مع المؤسسة عبر البريد الإلكتروني في الوقت الحالي.',
  'Back top': 'العودة إلى الأعلى',
  'Built around compassion, dignity, and accountability.': 'مبني على الرحمة والكرامة والمساءلة.',
  'Donation total:': 'إجمالي التبرع:',
  'Decrease quantity': 'تقليل الكمية',
  'Increase quantity': 'زيادة الكمية',
  'Remove item': 'حذف العنصر',
  'Baytak reached our family with dignity. The support arrived when we needed it most.': 'وصلت بيتك إلى أسرتنا بكرامة. جاء الدعم حين احتجناه أكثر.',
  'Volunteering with Baytak showed me how organised, transparent community work can change lives.': 'أظهر لي التطوع مع بيتك كيف يمكن للعمل المجتمعي المنظم والشفاف أن يغيّر الحيوات.',
  'I trust Baytak because I can see where monthly shares go — feeding, education, and medical care.': 'أثق في بيتك لأنني أرى أين تذهب الأسهم الشهرية — الإطعام والتعليم والرعاية الطبية.',
  'Quantity': 'الكمية',
  'Location': 'الموقع',
  'Unit': 'الوحدة',
  'Warehouse': 'المخزن',
  'Cases': 'الحالات',
  'المشروعات': 'المشروعات',
  'Create activity': 'إنشاء مشروع',
  'Activity (optional)': 'المشروع (اختياري)',
  'Project (optional)': 'المشروع (اختياري)',
  'Project': 'المشروع',
  'All projects': 'كل المشروعات',
  'No project — fund only': 'بدون مشروع — الصندوق فقط',
  'Required. This is the fund source (e.g. Zakat, Sadaqah).': 'مطلوب. هذا مصدر الصندوق (مثل الزكاة أو الصدقة).',
  'If selected (e.g. Education Program), the donation is also posted to that project’s Income (الدخل).': 'إذا اخترت مشروعاً (مثل برنامج التعليم)، يُضاف التبرع أيضاً إلى دخل ذلك المشروع.',
  'Choose a fund (donation type). Optionally link a project so the amount is posted to that project’s income ledger.': 'اختر الصندوق (نوع التبرع). ويمكن اختيار مشروع ليُقيَّد المبلغ في دخل ذلك المشروع.',
  'Fund (donation type)': 'الصندوق (نوع التبرع)',
  'Income by activity': 'الدخل حسب المشروع',
  'Top activities': 'أعلى المشروعات',
  'Activity income': 'دخل المشروعات',
  'Activity expense': 'مصروف المشروعات',
  'Activity balance': 'رصيد المشروعات',
  'Unified ledger': 'دفتر الأستاذ الموحد',
  'Add income': 'إضافة دخل',
  'Add expense': 'إضافة مصروف',
  'Back to list': 'العودة للقائمة',
  'Financial projects and their ledgers.': 'المشروعات المالية ودفاتر حساباتها.',
  'Each project has its own ledger. Balances are calculated, never stored.': 'لكل مشروع دفتر حساب خاص. الأرصدة تُحسب ولا تُخزَّن.',
  'Fund is taken automatically from the custody assignment. You only enter expense details.': 'يُؤخذ الصندوق تلقائياً من العُهدة. أدخل تفاصيل المصروف فقط.',
  'Fund is inherited by expenses automatically.': 'يُورَّث الصندوق للمصروفات تلقائياً.',
  'Inventory': 'المخزون',
  'Track stock, supplies, and storage locations used by Baytak programmes.': 'تتبع المخزون والمستلزمات ومواقع التخزين المستخدمة في برامج بيتك.',
  'Add item': 'إضافة صنف',
  'Search name, SKU, or location': 'ابحث بالاسم أو الرمز أو الموقع',
  'Item': 'الصنف',
  'SKU': 'الرمز',
  'No warehouse items': 'لا توجد أصناف في المخزن',
  'Add supplies and materials to start tracking stock.': 'أضف المستلزمات والمواد لبدء تتبع المخزون.',
  'Edit warehouse item': 'تعديل صنف المخزن',
  'Add warehouse item': 'إضافة صنف للمخزن',
  'Item name': 'اسم الصنف',
  'Active in warehouse': 'نشط في المخزن',
  'Create item': 'إنشاء الصنف',
  'Beneficiary support': 'دعم المستفيدين',
  'Register and follow medical, food, and emergency support cases.': 'سجّل وتابع الحالات الطبية والغذائية وحالات الطوارئ.',
  'Add case': 'إضافة حالة',
  'Name, phone, or case number': 'الاسم أو الهاتف أو رقم الحالة',
  'All priorities': 'كل الأولويات',
  'Low': 'منخفضة',
  'Medium': 'متوسطة',
  'High': 'مرتفعة',
  'Urgent': 'عاجلة',
  'Medical, feeding…': 'طبية، إطعام…',
  'Case': 'الحالة',
  'Category': 'التصنيف',
  'Priority': 'الأولوية',
  'Requested': 'المطلوب',
  'No cases found': 'لا توجد حالات',
  'Register a support case to begin follow-up.': 'سجّل حالة دعم لبدء المتابعة.',
  'Edit case': 'تعديل الحالة',
  'Case number': 'رقم الحالة',
  'Auto if empty': 'يُنشأ تلقائياً إن تُرك فارغاً',
  'Beneficiary name': 'اسم المستفيد',
  'Medical, feeding, education…': 'طبية، إطعام، تعليم…',
  'Open': 'مفتوحة',
  'In progress': 'قيد التنفيذ',
  'Closed': 'مغلقة',
  'Requested amount (EGP)': 'المبلغ المطلوب (جنيه)',
  'Approved amount (EGP)': 'المبلغ المعتمد (جنيه)',
  'Create case': 'إنشاء الحالة',
  'No phone': 'لا يوجد هاتف',
  'No notes': 'لا توجد ملاحظات',
}

const english = Object.fromEntries(Object.entries(arabic).map(([key, value]) => [value, key]))

function localizedValue(value: string, locale: Locale) {
  return (locale === 'ar' ? arabic[value] : english[value]) ?? value
}

function localizedText(value: string, locale: Locale) {
  const leading = value.match(/^\s*/)?.[0] ?? ''
  const trailing = value.match(/\s*$/)?.[0] ?? ''
  const text = value.trim()
  const direct = localizedValue(text, locale)
  if (direct !== text) return `${leading}${direct}${trailing}`

  if (locale === 'ar') {
    const donors = text.match(/^(\d+) donors$/)
    if (donors) return `${leading}${donors[1]} متبرع${trailing}`
    const donations = text.match(/^(\d+) donations$/)
    if (donations) return `${leading}${donations[1]} تبرع${trailing}`
    const identifier = text.match(/^ID #(\d+)$/)
    if (identifier) return `${leading}المعرّف #${identifier[1]}${trailing}`
  } else {
    const donors = text.match(/^(\d+) متبرع$/)
    if (donors) return `${leading}${donors[1]} donors${trailing}`
    const donations = text.match(/^(\d+) تبرع$/)
    if (donations) return `${leading}${donations[1]} donations${trailing}`
    const identifier = text.match(/^المعرّف #(\d+)$/)
    if (identifier) return `${leading}ID #${identifier[1]}${trailing}`
  }
  return value
}

function translateSubtree(node: Node, locale: Locale) {
  if (node.nodeType === Node.TEXT_NODE) {
    const translated = localizedText(node.nodeValue ?? '', locale)
    if (translated !== node.nodeValue) node.nodeValue = translated
    return
  }
  if (!(node instanceof HTMLElement) || ['SCRIPT', 'STYLE', 'CODE', 'SVG'].includes(node.tagName)) return

  for (const attribute of ['placeholder', 'aria-label', 'title']) {
    const value = node.getAttribute(attribute)
    if (!value) continue
    const translated = localizedText(value, locale)
    if (translated !== value) node.setAttribute(attribute, translated)
  }
  for (const child of node.childNodes) translateSubtree(child, locale)
}

interface LocaleContextValue {
  locale: Locale
  setLocale: (locale: Locale) => void
}

const LocaleContext = createContext<LocaleContextValue | null>(null)

function initialLocale(): Locale {
  const saved = window.localStorage.getItem(localeStorageKey)
  if (saved === 'ar' || saved === 'en') return saved
  return brand.defaultLocale
}

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(initialLocale)

  useEffect(() => {
    window.localStorage.setItem(localeStorageKey, locale)
    document.documentElement.lang = locale
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr'
    document.title = locale === 'ar' ? `${brand.appName} | العربية` : brand.appName

    const root = document.getElementById('root')
    if (!root) return
    translateSubtree(root, locale)
    const observer = new MutationObserver((records) => {
      for (const record of records) {
        if (record.type === 'characterData') translateSubtree(record.target, locale)
        for (const node of record.addedNodes) translateSubtree(node, locale)
      }
    })
    observer.observe(root, { childList: true, characterData: true, subtree: true })
    return () => observer.disconnect()
  }, [locale])

  const value = useMemo(() => ({ locale, setLocale }), [locale])
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>
}

export function useLocale() {
  const context = useContext(LocaleContext)
  if (!context) throw new Error('useLocale must be used inside LocaleProvider')
  return context
}

export function LanguageSwitcher() {
  const { locale, setLocale } = useLocale()
  return (
    <div className="language-switcher" aria-label="Language selector">
      <button className={locale === 'en' ? 'selected' : ''} type="button" onClick={() => setLocale('en')}>EN</button>
      <button className={locale === 'ar' ? 'selected' : ''} type="button" onClick={() => setLocale('ar')}>العربية</button>
    </div>
  )
}
