---
- name: Deploy/Upgrade Baytak Helm Chart
  hosts: all
  become: true
  gather_facts: true


  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python

    release_name: baytak
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml
    k3s_namespace: baytak
    # Images
    backend_repo: "abdelwahabadam/baytak"
    frontend_repo: "abdelwahabadam/baytak"

    backend_tag: "{{ backend_tag | default('backend-latest') }}"
    frontend_tag: "{{ frontend_tag | default('frontend-latest') }}"
  vars_files:
    - group_vars/all/vault.yml


  tasks:

    - name: Deploy/Upgrade Helm Release
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"

        name: "{{ release_name }}"
        chart_ref: "{{ chart_path }}"

        release_namespace: "{{ k3s_namespace }}"
        create_namespace: true
        release_state: present

        atomic: true
        wait: true
        wait_timeout: 10m
        reuse_values: true

        values:

          ###########################################################
          # Backend
          ###########################################################

          backend:
            image:
              repository: "{{ backend_repo }}"
              tag: "{{ backend_tag }}"
              pullPolicy: Always

          ###########################################################
          # Frontend
          ###########################################################

          frontend:
            image:
              repository: "{{ frontend_repo }}"
              tag: "{{ frontend_tag }}"
              pullPolicy: Always

          ###########################################################
          # Backend Secret
          ###########################################################

          backendSecret:
            DATABASE_USER: "{{ DATABASE_USER }}"
            DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"

            JWT_SECRET_KEY: "{{ JWT_SECRET_KEY }}"

            BOOTSTRAP_ADMIN_EMAIL: "{{ BOOTSTRAP_ADMIN_EMAIL }}"
            BOOTSTRAP_ADMIN_PASSWORD: "{{ BOOTSTRAP_ADMIN_PASSWORD }}"

            SMTP_USERNAME: "{{ SMTP_USERNAME }}"
            SMTP_PASSWORD: "{{ SMTP_PASSWORD }}"
            SMTP_FROM: "{{ SMTP_FROM }}"

          ###########################################################
          # DockerHub Secret
          ###########################################################

          registry:
            username: "{{ dockerhub_username }}"
            password: "{{ dockerhub_token }}"
            email: "{{ dockerhub_email }}"

      register: helm_deploy

    - name: Show deployment summary
      debug:
        msg:
          - "Helm Release : {{ release_name }}"
          - "Backend      : {{ backend_repo }}:{{ backend_tag }}"
          - "Frontend     : {{ frontend_repo }}:{{ frontend_tag }}"

    - name: Show Helm module output
      debug:
        var: helm_deploy

    - name: Get Helm release information
      kubernetes.core.helm_info:
        kubeconfig: "{{ kubeconfig_path }}"
        release_namespace: "{{ k3s_namespace }}"
        release_name: "{{ release_name }}"
      register: helm_info

    - name: Display Helm release information
      debug:
        var: helm_info.status

    - name: Wait for backend rollout
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: apps/v1
        kind: Deployment
        namespace: baytak
        name: backend-deployment
      register: backend_status
      retries: 30
      delay: 10
      until: >
        backend_status.resources[0].status.availableReplicas ==
        backend_status.resources[0].status.replicas

    - name: Wait for frontend rollout
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: apps/v1
        kind: Deployment
        namespace: baytak
        name: frontend-deployment
      register: frontend_status
      retries: 30
      delay: 10
      until: >
        frontend_status.resources[0].status.availableReplicas ==
        frontend_status.resources[0].status.replicas

    - name: Deployment completed
      debug:
        msg:
          - "Baytak deployment completed successfully."
          - "Backend image : {{ backend_repo }}:{{ backend_tag }}"
          - "Frontend image: {{ frontend_repo }}:{{ frontend_tag }}"