##   replicas: {{ .Values.backend.replicas }}


backend:
  replicas: 2
  image: baytak/be:latest
  port: 8000
  configMap: backend-config
  secret: backend-secret
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  replicas: 2
  image: baytak/frontend:latest
  port: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

postgres:
  replicas: 1
  image: postgres:16-alpine
  port: 5432
  dbName: charity
  userName: charity
  password: password
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  pv:
    storage: 5Gi
  pvc:
    storage: 5Gi

namespace:
  name: baytak

configmap:
  data:
    APP_NAME: "Baytak Foundation API"
    DATABASE_HOST: "db-service"
    DATABASE_PORT: "5432"
    DATABASE_NAME: "charity"
    CORS_ORIGINS: "http://localhost:8080,http://localhost:5173"
    FRONTEND_APP_URL: "http://localhost:8080"
    PASSWORD_RESET_MINUTES: "30"
    REPORT_STORAGE_PATH: "/app/reports"
    SCHEDULER_ENABLED: "true"
    SMTP_HOST: "smtp.gmail.com"
    SMTP_PORT: "587"
    SMTP_STARTTLS: "true"


ingress:
  enabled: true
  className: nginx
  host: baytak.local
  paths:
    none:
      serviceName: frontend-service
      servicePort: 80
    api:
      serviceName: backend-service
      servicePort: 8000

issuer:
  spec:
    email: "hopaasd1997@gmail.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"

secret:
  POSTGRES_USER: "charity"
  POSTGRES_PASSWORD: "password"

  JWT_SECRET_KEY: "your-super-secret-key"

  BOOTSTRAP_ADMIN_EMAIL: "admin@charity.local"
  BOOTSTRAP_ADMIN_PASSWORD: "adminpassword"

  SMTP_USERNAME: "your-email@gmail.com"
  SMTP_PASSWORD: "your-app-password"
  SMTP_FROM: "your-email@gmail.com"